var resources = {
    en: {
        translation:
            {
                'tasks': 'Tasks',
                'activities': 'Activities',
                'home': 'Home',
                "Abbreviation":"Abbreviation",
        "AbbreviationAr":"Arabic Abbreviation",
        "AbbreviationEn":"English Abbreviation",
        "Add":"Add",
        "AddRelated":"Add Related",
        "AdvancedSearch":"Advanced Search",
        "All":"All",
        "AllTasks":"All tasks",
        "Archive":"Archive",
        "Archived":"Archived",
        "ArchiveID":"Archive ID",
        "AssignedBy":"Assigned By",
        "AssignedTo":"Assigned To",
        "AssignTo":"Assign To",
        "Attachments":"Attachments",
        "Back":"Back",
        "CanAdd":"Add",
        "Cancel":"Cancel",
        "CanDelete":"Delete",
        "CanEdit":"Edit",
        "Category":"Category",
        "ClickHere":"Please click here to complete the task",
        "Close":"Close",
        "CloseBoth":"Close Correspondence and Task",
        "CloseBoth1":"Close Correspondence and Task",
        "CloseCorrespondence":"Close Correspondence",
        "ClosedByUser":"Closed By User",
        "Comments":"Comments",
        "Completed":"Completed",
        "CompletedDate":"Completed Date",
        "Confidential":"Confidential",
        "CorrespondenceDate":"Correspondence Date",
        "CorrespondenceDetails":"Correspondence Details",
        "CorrespondencesTasks":"Correspondences Tasks",
        "CorrespondenceStatus":"Correspondence Status",
        "CorrespondenceTitle":"Correspondence Title",
        "CorrespondenceType":"Correspondence Type",
        "Created":"Created",
        "CreatedBy":"Created By",
        "DateArchived":"Date Archived",
        "DateCompleted":"DateCompleted",
        "DateReceived":"Date Received",
        "DateRecRequired":"Date received is required",
        "DateSent":"Date Sent",
        "DateSentReq":"Date sent is required",
        "Deleted":"Deleted",
        "Department":"Department",
        "DeptRef":"Department Ref",
        "DeptType":"Department Type",
        "Description":"Desctiption",
        "Details":"Details",
        "Details1":"Details",
        "Direction":"Direction",
        "DirectionType":"Direction Type",
        "Division":"Division",
        "Draft":"Draft",
        "DueDate":"Due Date",
        "DueDateReq":"Due Date is required",
        "Edit":"تعديل",
        "Email":"Email",
        "EndDate":"End Date",
        "External":"External",
        "FileLocation":"File Location",
        "FileName":"File Name",
        "FileType":"File Type",
        "Followup":"Follow up",
        "FullName":"Full Name",
        "FullNameAr":"Arabic Full Name",
        "Hide":"Hide",
        "High":"High",
        "ID":"ID",
        "Incoming":"Incoming",
        "IncomingInternal":"Incoming Internal",
        "Internal":"Internal",
        "ItemsCountInfo":"<b>{0}</b> items out of <b>{1}</b>",
        "JobDescription":"Job Description",
        "JobDescriptionAr":"Arabic Job Description",
        "JobTitle":"Job Title",
        "JobTitleAr":"Arabic Job Title",
        "Language":"language",
        "Login":"Login",
        "Low":"Low",
        "Medium":"Medium",
        "MessageType":"Message Type",
        "Modified":"Modified",
        "ModifiedBy":"Modified By",
        "Module":"Module",
        "MyTasks":"My Tasks",
        "NoRecords":"No records found",
        "OpenTask":"Continue to task",
        "Outgoing":"Outgoing",
        "OutGoingInternal":"OutGoing Internal",
        "PagerText":"Change page: {4} &nbsp;Page <strong>{0}</strong> of <strong>{1}</strong>, items <strong>{2}</strong> to <strong>{3}</strong> of <strong>{5}</strong>.",
        "PageSize":"Page Size:",
        "Password":"Password",
        "Pending":"Pending",
        "Permissions":"Permissions",
        "PostType":"Post type",
        "Priority":"Priority",
        "ReferenceNumber":"Reference Number",
        "ReferenceNumberIncoming":"Incoming Reference Number",
        "ReferenceNumberOutgoing":"Outgoing Reference Number",
        "RefRequired":"Reference number is required",
        "RelatedContact":"Contact",
        "RelatedCorrespondences":"Related Correspondences",
        "RelatedEntities":"Related Entities",
        "RelatedEntity":"Re",
        "RelatedEntityDescription":"Related Entity Description",
        "RelatedEntityDescriptionIncoming":"Related Entity Description",
        "RelatedEntityDescriptionOutgoing":"Related Entity Description",
        "RelatedEntityID":"Related Entity ID",
        "RelatedEntityIDIncoming":"Related Entity ID",
        "RelatedEntityIDOutgoing":"Related Entity ID",
        "RelatedEntityReq":"Related entity is required",
        "RelatedEntityType":"Related Entity Type",
        "RelatedEntityTypeIncoming":"Related Entity Type",
        "RelatedEntityTypeOutgoing":"Related Entity Type",
        "RelatedEntityTypeRequired":"Related entity type is required",
        "RelatedJobTitle":"Job Title",
        "RepliedByCorr":"Replied by correspondence with serial: {0}",
        "ReplyByCorr":"Reply by Correspondence",
        "ResponsibleID":"Responsible User",
        "ResponsibleIDIncoming":"Responsible User",
        "ResponsibleIDOutgoing":"Sender",
        "ResponsibleRequired":"Responsible user is required",
        "Return":"Return",
        "RoutedBy":"RoutedBy",
        "RoutedTo":"Routed To",
        "Save":"Save",
        "SaveCompleted":"Save Completed",
        "ScopeName":"Scope",
        "Search":"Search",
        "SearchText":"Search Word",
        "Section":"Section",
        "SelectCorrespondenceType":"Select Correspondence Type",
        "SelectUser":"Select User",
        "SendType":"Message Send Type",
        "SentDate":"Sent On",
        "SentTo":"Sent To",
        "SentToRequired":"Sent to is required",
        "SequenceNo":"Reference No.",
        "Serial":"Serial",
        "ShowReport":"Show Report",
        "SimpleSearch":"Simple Search",
        "StartDate":"Start Date",
        "Status":"Status",
        "SubCategory":"SubCategory",
        "Subject":"Subject",
        "Submit":"Submit",
        "TaskDetails":"Task Details",
        "Tasks":"Correspondence Module Tasks",
        "TaskType":"Task Type",
        "Title":"Title",
        "TitleRequired":"Title is required",
        "UserName":"User Name",
        "Version":"Version"
            }
    },
    ar: {
        translation: {
            'tasks': 'المهام',
            'activities': 'النشاطات',
            'home': 'الصفحة الرئيسية',
            "Abbreviation": "الاختصار",
            "AbbreviationAr": "الاختصار العربي",
            "AbbreviationEn": "الاختصار الانجليزي",
            "Add": "إضافة",
            "AddRelated": "إختيار مرتبط",
            "AdvancedSearch": "بحث متقدم",
            "All": "الكل",
            "AllTasks": "كل المهام",
            "Archive": "أرشفة",
            "Archived": "مؤرشف",
            "ArchiveID": "رمز الأرشيف",
            "AssignedBy": "مسندة من",
            "AssignedTo": "مسندة إلى",
            "AssignTo": "تعيين إلى",
            "Attachments": "المرفقات",
            "Back": "رجوع",
            "CanAdd": "إضافة",
            "Cancel": "رجوع",
            "CanDelete": "حذف",
            "CanEdit": "تعديل",
            "Category": "التصنيف",
            "ClickHere": "الرجاء الضغط هنا لمتابعة المهمة",
            "Close": "إغلاق",
            "CloseBoth": "إغلاق المهمة و المراسلة",
            "CloseCorrespondence": "إغلاق المراسلة",
            "ClosedByUser": "تم الاغلاق من قبل المستخدم",
            "Comments": "ملاحظات",
            "Completed": "منجز",
            "CompletedDate": "تارخ الانجاز",
            "Confidential": "سري",
            "CorrespondenceDate": "تاريخ المراسلة",
            "CorrespondenceDetails": "تفاصيل المراسلة",
            "CorrespondenceStatus": "حالة المراسلة",
            "CorrespondenceTitle": "عنوان المراسلة",
            "CorrespondenceType": "نوع المراسلة",
            "Created": "تاريخ الإنشاء",
            "CreatedBy": "الإنشاء بواسطة",
            "DateArchived": "تاريخ الأرشفة",
            "DateCompleted": "تاريخ الإتمام",
            "DateReceived": "تاريخ الإستلام",
            "DateRecRequired": "تاريخ الاستلام مطلوب",
            "DateSent": "تاريخ الرسالة",
            "DateSentReq": "تاريخ الارسال مطلوب",
            "Deleted": "محذوف",
            "Department": "الإدارة",
            "DeptRef": "رمز الجهة",
            "DeptType": "نوع الجهة",
            "Description": "محتوى الرسالة",
            "Details": "المضمون",
            "Details1": "التفاصيل",
            "Direction": "نوع المراسلة",
            "DirectionType": "نوع الاتجاه",
            "Division": "القطاع",
            "Draft": "مسودة",
            "DueDate": "الإستحقاق",
            "DueDateReq": "المتوجب مطلوب",
            "Edit": "تعديل",
            "Email": "البريد الإلكتروني",
            "EndDate": "تاريخ النهاية",
            "External": "خارجي",
            "FileLocation": "مكان الملف",
            "FileName": "إسم المرفق",
            "FileType": "نوع المرفق",
            "Followup": "متابعة",
            "FullName": "الإسم الكامل",
            "FullNameAr": "الإسم الكامل",
            "Hide": "إخفاء",
            "High": "عالي",
            "ID": "الرقم",
            "Incoming": "وارد",
            "IncomingInternal": "وارد داخلي",
            "Internal": "داخلي",
            "ItemsCountInfo": "<b>{0}</b> بند من أصل <b>{1}</b>",
            "JobDescription": "المسمى الوظيفي",
            "JobDescriptionAr": "المسمى الوظيفي",
            "JobTitle": "المسمى الوظيفي",
            "JobTitleAr": "المسمى الوظيفي",
            "Language": "اللغة",
            "Login": "دخول",
            "Low": "منخفض",
            "Medium": "متوسط",
            "MessageType": "نوع الصادر",
            "Modified": "اخر تعديل",
            "ModifiedBy": "اخر تعديل بواسطة",
            "Module": "وحدة",
            "MyTasks": "مهامي",
            "NoRecords": "لا يوجد بيانات",
            "OpenTask": "مراجعة المهمة",
            "Outgoing": "صادر",
            "OutGoingInternal": "صادر داخلي",
            "PagerText": "تغيير الصفحة: {4} &nbsp;الصفحة <strong>{0}</strong> من <strong>{1}</strong>&nbsp;&nbsp; [مواد <strong>{2}</strong> إلى <strong>{3}</strong> من أصل <strong>{5}</strong>]",
            "PageSize": "حجم الصفحة:",
            "Password": "كلمة المرور",
            "Pending": "في الإنتظار",
            "Permissions": "الصلاحيات",
            "PostType": "نوع الصادر",
            "Priority": "الأهمية",
            "ReferenceNumber": "رمز المرجع",
            "ReferenceNumberIncoming": "رقم المرجع",
            "ReferenceNumberOutgoing": "رقم المرجع",
            "RefRequired": "رقم المرجع مطلوب",
            "RelatedContact": "موجهة الى",
            "RelatedCorrespondences": "المراسلات المرتبطة",
            "RelatedEntities": "الجهات ذات صلة",
            "RelatedEntity": "الجهة",
            "RelatedEntityDescription": "الوصف",
            "RelatedEntityDescriptionIncoming": "وصف جهة الورود",
            "RelatedEntityDescriptionOutgoing": "وصف المرسل له",
            "RelatedEntityID": "رمز الجهة المتصلة",
            "RelatedEntityIDIncoming": "جهة الورود",
            "RelatedEntityIDOutgoing": "المرسل له",
            "RelatedEntityReq": "الجهة مطلوبة",
            "RelatedEntityType": "نوع الجهة المرتبطة",
            "RelatedEntityTypeIncoming": "نوع جهة الورود",
            "RelatedEntityTypeOutgoing": "نوع التوجيه",
            "RelatedEntityTypeRequired": "الجهة المرتبطة مطلوبة",
            "RelatedJobTitle": "المسمى الوظيفي",
            "RepliedByCorr": "تم الرد بمراسلة ذو رقم المتسلسل: {0}",
            "ReplyByCorr": "رد عبر مراسلة",
            "ResponsibleID": "المسؤول",
            "ResponsibleIDIncoming": "المسؤول",
            "ResponsibleIDOutgoing": "المرسل",
            "ResponsibleRequired": "المسؤول مطلوب",
            "Return": "إعادة",
            "RoutedBy": "حولت من قبل",
            "RoutedTo": "التحويل الى",
            "Save": "حفظ",
            "SaveCompleted": "حفظ منجز",
            "ScopeName": "المجال",
            "Search": "إبحث",
            "SearchText": "كلمة البحث",
            "Section": "القسم",
            "SelectCorrespondenceType": "اختر نوع المراسلة",
            "SelectUser": "إختر مستخدم",
            "SendType": "نوع الإرسال",
            "SentDate": "أرسلت بتاريخ",
            "SentTo": "المرسل إليه",
            "SentToRequired": "المرسل إليه مطلوب",
            "SequenceNo": "المتسلسل",
            "Serial": "الرقم المتسلسل",
            "ShowReport": "إظهار التقرير",
            "SimpleSearch": "بحث بسيط",
            "StartDate": "تاريخ اليدء",
            "Status": "الحالة",
            "SubCategory": "SubCategory",
            "Subject": "الموضوع",
            "Submit": "حفظ و إرسال",
            "TaskDetails": "تفاصيل المهمة",
            "Tasks": "المهام",
            "TaskType": "نوع المهمة",
            "Title": "الموضوع",
            "TitleRequired": "العنوان مطلوب",
            "UserName": "إسم المستخدم",
            "Version": "رقم النسخة"
        }
    },
};