//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Mobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Id { get; set; }
        public Nullable<int> AttachmentTypeId { get; set; }
        public string FileLocation { get; set; }
        public string FileName { get; set; }
        public string RelatedTable { get; set; }
        public Nullable<int> RelatedId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
    }
}
