//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Mobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDependency
    {
        public int Task1Id { get; set; }
        public int Task2Id { get; set; }
        public string DepedencyType { get; set; }
        public string Comments { get; set; }
    }
}
