//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCA.Mobile.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskResult
    {
        public TaskResult()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
